# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'HalfCandyAnimation' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HalfCandyAnimation
pod 'SDWebImage'
pod 'AFNetworking'
pod 'MJExtension'
end
